
rev:
	g++ Reverse_Polish_notation.cpp
	./a.out < test
	rm ./a.out

main:
	g++ main.cpp
	./a.out < test
	rm ./a.out


rev_val:
	g++ -Wall -Wextra -g Reverse_Polish_notation.cpp
	valgrind ./a.out < test
	rm ./a.out

main_val:
	g++ -Wall -Wextra -g Reverse_Polish_notation.cpp
	valgrind ./a.out < test
	rm ./a.out