
CFLAGS = -Wall -Wextra -Werror -pthread -g -o game
COMP = gcc

game: main.c
	$(COMP) $(CFLAGS) main.c utility/utility.c utility/functions.c SystemErrors/errors.c
#	time ./game 8 33 22 44 55 67
#	rm game
